package fi.helsinki.cs.tmc.intellij.ui.courseselection;

import fi.helsinki.cs.tmc.core.domain.Course;

import javax.swing.text.DefaultCaret;
import java.awt.*;

public class CourseCard extends javax.swing.JPanel {

    private Course course;

    /**
     * Creates new form CourseCard
     */
    public CourseCard(Course course) {
        initComponents();

        this.course = course;

        DefaultCaret caret = (DefaultCaret)this.informationLabel.getCaret();
        caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);

        this.titleLabel.setText(course.getTitle());
        String information = course.getDescription();
//        if (information.length() > 100) {
//            information = information.substring(0, 99) + "...";
//        }
        this.informationLabel.setText(information);
        this.informationLabel.setRows(2);
        final String text = this.informationLabel.getText();
        if (text.length() > 3) {
            this.informationLabel.replaceRange("...", text.length() - 3, text.length());
        }
        this.nameLabel.setText("/" + course.getName());
    }

    public Course getCourse() {
        return this.course;
    }

    public void setColors(Color foreground, Color background) {
        this.setBackground(background);
        this.titleLabel.setForeground(foreground);
        this.nameLabel.setForeground(foreground);
        this.infoScrollPane.setBackground(background);
        this.informationLabel.setForeground(foreground);
        this.informationLabel.setBackground(background);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        infoScrollPane = new javax.swing.JScrollPane();
        informationLabel = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(332, 73));
        setMinimumSize(new java.awt.Dimension(332, 73));
        setPreferredSize(new java.awt.Dimension(346, 107));

//        titleLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
//        org.openide.awt.Mnemonics.setLocalizedText(titleLabel, org.openide.util.NbBundle.getMessage(CourseCard.class, "CourseCard.titleLabel.text")); // NOI18N
//
//        nameLabel.setForeground(new java.awt.Color(150, 150, 150));
//        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(CourseCard.class, "CourseCard.nameLabel.text")); // NOI18N
//
//        infoScrollPane.setBackground(new java.awt.Color(255, 255, 255));
//        infoScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
//        infoScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
//        infoScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
//        infoScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
//        infoScrollPane.setHorizontalScrollBar(null);
//        infoScrollPane.setPreferredSize(new java.awt.Dimension(106, 30));
//
//        informationLabel.setEditable(false);
//        informationLabel.setBackground(new java.awt.Color(255, 255, 255));
//        informationLabel.setLineWrap(true);
//        informationLabel.setText(org.openide.util.NbBundle.getMessage(CourseCard.class, "CourseCard.informationLabel.text")); // NOI18N
//        informationLabel.setWrapStyleWord(true);
//        informationLabel.setAutoscrolls(false);
//        informationLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
//        informationLabel.setMaximumSize(null);
//        infoScrollPane.setViewportView(informationLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(titleLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                                                .addComponent(nameLabel))
                                        .addComponent(infoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titleLabel)
                                        .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(infoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea informationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}